In [ ]:
!pip install -q kaggle

In [ ]:
from google.colab import files
files.upload()

Saving match_events.csv to match_events.csv
Saving match_lineups.csv to match_lineups.csv
Saving match_prediction_features.csv to match_prediction_features.csv
Saving match_team_stats.csv to match_team_stats.csv
Saving matches.csv to matches.csv
Saving matches_detailed.csv to matches_detailed.csv
Saving player_stats.csv to player_stats.csv
Saving referees.csv to referees.csv
Saving squads_and_players.csv to squads_and_players.csv
Saving teams.csv to teams.csv
Saving tournament_stages.csv to tournament_stages.csv
Saving venues.csv to venues.csv

{'match_events.csv': b'event_id,match_id,minute,event_type,team_id,player_id\r\n1,1,17,Yellow Card,2,30\r\n2,1,23,Yellow Card,1,26\r\n3,1,55,Red Card,2,39\r\n4,1,55,VAR Review,2,39\r\n5,1,67,Goal,1,9\r\n6,1,67,Assist,1,25\r\n7,1,74,Yellow Card,2,45\r\n8,1,84,Red Card,2,37\r\n9,1,86,Red Card,1,3\r\n10,1,9,Goal,1,16\r\n11,1,9,Assist,1,6\r\n12,2,59,Goal,4,85\r\n13,2,59,Assist,4,83\r\n14,2,67,Goal,3,58\r\n15,2,67,Assist,3,71\r\n16,2,80,Goal,3,70\r\n17,2,80,Assist,3,58\r\n18,2,90,Yellow Card,3,55\r\n19,3,11,Yellow Card,5,106\r\n20,3,21,Goal,6,155\r\n21,3,21,Assist,6,135\r\n22,3,44,Yellow Card,6,140\r\n23,3,45,Yellow Card,6,155\r\n24,3,53,Yellow Card,5,108\r\n25,3,78,Goal,5,113\r\n26,3,78,Assist,5,128\r\n27,3,90,Yellow Card,6,148\r\n28,4,31,Goal,13,332\r\n29,4,31,Assist,13,322\r\n30,4,45,Goal,13,332\r\n31,4,45,Assist,13,329\r\n32,4,53,Yellow Card,14,348\r\n33,4,59,Yellow Card,13,316\r\n34,4,7,Goal,13,354\r\n35,4,73,Goal,14,349\r\n36,4,73,Assist,14,357\r\n37,4,79,Yellow Card,14,346\r\n38,4,88,Yellow Card,14,356\r\n39,4,9,Yellow Card,14,342\r\n40,4,90,Goal,13,319\r\n41,4,90,Assist,13,328\r\n42,4,90,Yellow Card,14,344\r\n43,5,14,Yellow Card,7,157\r\n44,5,17,Goal,8,189\r\n45,5,23,Yellow Card,7,161\r\n46,5,42,Yellow Card,8,188\r\n47,5,90,Goal,7,184\r\n48,6,21,Goal,10,245\r\n49,6,21,Assist,10,244\r\n50,6,32,Goal,9,215\r\n51,6,32,Assist,9,216\r\n52,6,37,Yellow Card,9,213\r\n53,6,43,Yellow Card,9,232\r\n54,7,28,Goal,12,293\r\n55,7,39,Yellow Card,11,270\r\n56,7,46,Yellow Card,12,288\r\n57,7,90,Yellow Card,12,309\r\n58,7,90,Yellow Card,12,311\r\n59,8,27,Goal,15,381\r\n60,8,27,Assist,15,388\r\n61,8,75,Goal,15,372\r\n62,8,86,Yellow Card,16,409\r\n63,9,21,Goal,18,450\r\n64,9,38,Goal,17,431\r\n65,9,38,Assist,17,434\r\n66,9,45,Goal,17,423\r\n67,9,47,Goal,17,426\r\n68,9,47,Assist,17,422\r\n69,9,6,Goal,17,439\r\n70,9,6,Assist,17,433\r\n71,9,68,Goal,17,434\r\n72,9,68,Assist,17,442\r\n73,9,78,Goal,17,442\r\n74,9,78,Assist,17,422\r\n75,9,88,Goal,17,423\r\n76,9,88,Assist,17,442\r\n77,10,50,Goal,21,524\r\n78,10,50,Assist,21,528\r\n79,10,57,Goal,22,559\r\n80,10,57,Assist,22,554\r\n81,10,61,Yellow Card,21,544\r\n82,10,64,Goal,21,544\r\n83,10,64,Assist,21,528\r\n84,10,83,Yellow Card,21,530\r\n85,10,88,Goal,22,561\r\n86,10,88,Assist,22,565\r\n87,10,90,Yellow Card,21,535\r\n88,11,28,Yellow Card,19,474\r\n89,11,38,Yellow Card,19,476\r\n90,11,40,Yellow Card,19,485\r\n91,11,73,Yellow Card,20,519\r\n92,11,90,Goal,19,483\r\n93,11,90,Assist,19,473\r\n94,12,30,Goal,23,581\r\n95,12,30,Assist,23,589\r\n96,12,43,Goal,24,602\r\n97,12,43,Assist,24,608\r\n98,12,54,Yellow Card,24,611\r\n99,12,59,Goal,23,589\r\n100,12,59,Assist,23,581\r\n101,12,7,Goal,23,590\r\n102,12,84,Goal,23,591\r\n103,12,84,Assist,23,581\r\n104,12,90,Goal,23,590\r\n105,12,90,Assist,23,579\r\n106,13,16,Yellow Card,30,767\r\n107,13,90,Yellow Card,29,748\r\n108,14,13,Yellow Card,26,669\r\n109,14,14,Yellow Card,25,645\r\n110,14,19,Goal,26,658\r\n111,14,19,Assist,26,660\r\n112,14,34,Yellow Card,26,663\r\n113,14,66,Goal,25,653\r\n114,14,75,Yellow Card,25,629\r\n115,15,41,Goal,31,784\r\n116,15,44,Yellow Card,31,784\r\n117,15,80,Goal,32,826\r\n118,16,32,Goal,27,699\r\n119,16,54,Goal,28,713\r\n120,16,54,Assist,28,711\r\n121,16,64,Goal,27,684\r\n122,16,64,Assist,27,699\r\n123,16,7,Goal,28,713\r\n124,16,7,Assist,28,711\r\n125,16,89,Yellow Card,27,679\r\n126,17,66,Goal,33,842\r\n127,17,66,Assist,33,843\r\n128,17,82,Goal,33,844\r\n129,17,82,Assist,33,846\r\n130,17,90,Goal,33,842\r\n131,17,90,Assist,33,843\r\n132,17,90,Goal,34,878\r\n133,17,90,Assist,34,871\r\n134,18,29,Goal,36,919\r\n135,18,29,Assist,36,915\r\n136,18,39,Goal,35,902\r\n137,18,39,Assist,35,900\r\n138,18,43,Goal,36,919\r\n139,18,76,Goal,36,914\r\n140,18,76,Assist,36,920\r\n141,18,86,Yellow Card,35,888\r\n142,18,90,Goal,36,902\r\n143,19,17,Goal,37,946\r\n144,19,17,Assist,37,943\r\n145,19,60,Goal,37,946\r\n146,19,76,Goal,37,946\r\n147,19,76,Assist,37,951\r\n148,20,20,Goal,39,1006\r\n149,20,20,Assist,39,992\r\n150,20,50,Goal,40,1023\r\n151,20,50,Assist,40,1022\r\n152,20,76,Goal,39,1019\r\n153,20,77,Yellow Card,39,997\r\n154,20,90,Goal,39,995\r\n155,21,13,Yellow Card,41,1050\r\n156,21,32,Yellow Card,42,1088\r\n157,21,45,Goal,42,1086\r\n158,21,45,Assist,42,1092\r\n159,21,6,Goal,41,1055\r\n160,21,6,Assist,41,1058\r\n161,21,88,Yellow Card,41,1042\r\n162,21,90,Yellow Card,41,1044\r\n163,22,12,Goal,45,1153\r\n164,22,36,Goal,46,1186\r\n165,22,36,Assist,46,1187\r\n166,22,42,Goal,45,1153\r\n167,22,42,Assist,45,1148\r\n168,22,45,Goal,46,1196\r\n169,22,45,Assist,46,1184\r\n170,22,47,Goal,45,1154\r\n171,22,47,Assist,45,1152\r\n172,22,85,Goal,45,1155\r\n173,22,85,Assist,45,1151\r\n174,23,16,Yellow Card,47,1199\r\n175,23,72,Yellow Card,48,1224\r\n176,23,90,Goal,47,1199\r\n177,23,90,Assist,47,1207\r\n178,23,90,Yellow Card,48,1236\r\n179,24,34,Yellow Card,43,1094\r\n180,24,40,Goal,44,1120\r\n181,24,40,Assist,44,1125\r\n182,24,60,Goal,43,1114\r\n183,24,65,Goal,44,1125\r\n184,24,65,Assist,44,1132\r\n185,24,7,Yellow Card,44,1135\r\n186,24,90,Goal,44,1139\r\n187,24,90,Assist,44,1137\r\n188,25,4,Yellow Card,3,71\r\n189,25,50,Goal,1,7\r\n190,25,58,Yellow Card,3,60\r\n191,26,33,Yellow Card,2,30\r\n192,26,40,Yellow Card,2,31\r\n193,26,6,Goal,4,96\r\n194,26,6,Assist,4,102\r\n195,26,75,Yellow Card,4,85\r\n196,26,81,VAR Review,2,38\r\n197,26,83,Goal,2,30\r\n198,27,16,Goal,5,113\r\n199,27,29,Goal,5,114\r\n200,27,45,Goal,5,114\r\n201,27,60,Red Card,7,170\r\n202,27,60,VAR Review,7,170\r\n203,27,62,Yellow Card,7,176\r\n204,27,64,Goal,5,129\r\n205,27,75,Goal,5,182\r\n206,27,85,Red Card,7,179\r\n207,27,9,Yellow Card,5,117\r\n208,27,90,Goal,5,114\r\n209,27,90,Assist,5,129\r\n210,28,59,Yellow Card,6,137\r\n211,28,61,Yellow Card,6,141\r\n212,28,65,Yellow Card,8,186\r\n213,28,74,Goal,8,191\r\n214,28,74,Assist,8,192\r\n215,28,80,Red Card,6,134\r\n216,28,84,Goal,8,199\r\n217,28,84,Assist,8,189\r\n218,28,90,Goal,8,191\r\n219,28,90,Assist,8,199\r\n220,28,90,Goal,8,192\r\n221,28,90,Goal,6,156\r\n222,29,23,Goal,9,217\r\n223,29,36,Goal,9,217\r\n224,29,36,Assist,9,215\r\n225,29,4,Yellow Card,11,262\r\n226,29,45,Goal,9,215\r\n227,29,45,Assist,9,228\r\n228,29,45,Yellow Card,11,280\r\n229,29,65,Yellow Card,9,224\r\n230,29,72,Yellow Card,11,277\r\n231,30,2,Goal,10,245\r\n232,30,2,Assist,10,244\r\n233,30,23,Yellow Card,10,248\r\n234,30,65,Yellow Card,12,289\r\n235,31,11,Goal,13,385\r\n236,31,16,Yellow Card,15,369\r\n237,31,32,Yellow Card,15,367\r\n238,31,43,Goal,13,328\r\n239,31,43,Assist,13,314\r\n240,31,43,VAR Review,13,328\r\n241,31,56,Yellow Card,13,317\r\n242,31,89,Yellow Card,13,332\r\n243,31,89,Yellow Card,15,383\r\n244,31,89,Yellow Card,15,368\r\n245,31,90,Yellow Card,13,315\r\n246,32,2,Goal,14,361\r\n247,32,2,Assist,14,357\r\n248,32,4,Yellow Card,14,361\r\n249,32,45,Red Card,14,348\r\n250,32,45,VAR Review,14,348\r\n251,32,71,Yellow Card,16,403\r\n252,33,30,Goal,19,476\r\n253,33,30,Assist,19,479\r\n254,33,68,Goal,17,442\r\n255,33,68,Assist,17,436\r\n256,33,90,Goal,17,442\r\n257,33,90,Assist,17,439\r\n258,34,38,Yellow Card,20,499\r\n259,34,39,Yellow Card,18,452\r\n260,34,53,Yellow Card,18,449\r\n261,34,56,Yellow Card,18,450\r\n262,34,75,Yellow Card,18,445\r\n263,34,90,Yellow Card,18,461\r\n264,35,17,Goal,21,539\r\n265,35,17,Assist,21,542\r\n266,35,47,Goal,21,531\r\n267,35,47,Assist,21,542\r\n268,35,5,Goal,21,539\r\n269,35,5,Assist,21,531\r\n270,35,53,Yellow Card,23,577\r\n271,35,54,Goal,21,531\r\n272,35,54,Assist,21,544\r\n273,35,59,Goal,23,583\r\n274,35,59,Assist,23,581\r\n275,35,75,Yellow Card,23,590\r\n276,35,80,Yellow Card,23,579\r\n277,35,89,Goal,21,544\r\n278,35,89,Assist,21,530\r\n279,36,31,Goal,22,564\r\n280,36,31,Assist,22,559\r\n281,36,4,Goal,22,561\r\n282,36,4,Assist,22,559\r\n283,36,69,Goal,22,560\r\n284,36,69,Assist,22,564\r\n285,36,83,Goal,22,564\r\n286,36,83,Assist,22,570\r\n287,37,3,Yellow Card,25,633\r\n288,37,33,Yellow Card,27,682\r\n289,37,66,Red Card,25,649\r\n290,38,15,Goal,28,718\r\n291,38,15,Assist,28,704\r\n292,38,17,Yellow Card,26,667\r\n293,38,20,Yellow Card,28,712\r\n294,38,34,Yellow Card,28,722\r\n295,38,58,Goal,26,661\r\n296,38,58,Assist,26,653\r\n297,38,67,Goal,26,660\r\n298,38,67,Assist,26,661\r\n299,38,82,Goal,26,657\r\n300,38,82,Assist,26,660\r\n301,39,10,Goal,29,747\r\n302,39,10,Assist,29,749\r\n303,39,21,Goal,29,749\r\n304,39,21,Assist,29,742\r\n305,39,24,Goal,29,749\r\n306,39,24,Assist,29,738\r\n307,39,30,Yellow Card,31,790\r\n308,39,49,Goal,29,785\r\n309,39,60,Yellow Card,31,803\r\n310,40,20,Yellow Card,32,812\r\n311,40,21,Goal,30,760\r\n312,40,44,Goal,32,826\r\n313,40,44,Assist,32,814\r\n314,40,45,Goal,32,820\r\n315,40,45,Assist,32,826\r\n316,40,5,Yellow Card,30,767\r\n317,40,58,Yellow Card,32,822\r\n318,40,61,Goal,30,780\r\n319,40,90,Yellow Card,30,757\r\n320,41,14,Goal,33,842\r\n321,41,14,Assist,33,843\r\n322,41,54,Goal,33,842\r\n323,41,54,Assist,33,839\r\n324,41,6,Yellow Card,35,900\r\n325,41,66,Goal,33,839\r\n326,41,66,Assist,33,843\r\n327,42,43,Goal,36,926\r\n328,42,48,Goal,36,919\r\n329,42,48,Assist,36,920\r\n330,42,53,Goal,34,876\r\n331,42,53,Assist,34,868\r\n332,42,58,Goal,36,919\r\n333,42,58,Assist,36,916\r\n334,42,90,Goal,34,876\r\n335,42,90,Assist,34,869\r\n336,43,38,Goal,37,946\r\n337,43,38,Assist,37,961\r\n338,43,41,Yellow Card,39,993\r\n339,43,76,Yellow Card,37,961\r\n340,43,76,Yellow Card,39,1008\r\n341,43,90,Goal,37,946\r\n342,43,90,Yellow Card,37,941\r\n343,44,36,Goal,40,1035\r\n344,44,36,Assist,40,1024\r\n345,44,44,Yellow Card,38,968\r\n346,44,64,Yellow Card,40,1018\r\n347,44,69,Goal,38,974\r\n348,44,69,Assist,38,969\r\n349,44,82,Goal,38,971\r\n350,45,14,Yellow Card,43,1101\r\n351,45,17,Goal,41,1065\r\n352,45,39,Goal,41,1047\r\n353,45,39,Assist,41,1048\r\n354,45,6,Goal,41,1047\r\n355,45,6,Assist,41,1060\r\n356,45,60,Goal,41,1094\r\n357,45,68,Yellow Card,41,1053\r\n358,45,87,Goal,41,1057\r\n359,45,87,Assist,41,1063\r\n360,46,56,Yellow Card,44,1121\r\n361,46,76,Goal,44,1120\r\n362,46,76,Assist,44,1138\r\n363,46,90,Yellow Card,44,1134\r\n364,46,90,Yellow Card,42,1084\r\n365,47,41,Yellow Card,45,1148\r\n366,47,60,Yellow Card,47,1215\r\n367,48,54,Goal,46,1181\r\n368,48,54,Assist,46,1172\r\n369,48,61,Yellow Card,48,1233\r\n370,48,90,Yellow Card,46,1187\r\n371,49,55,Goal,1,20\r\n372,49,55,Assist,1,7\r\n373,49,61,Goal,1,16\r\n374,49,61,Assist,1,2\r\n375,49,64,Yellow Card,1,4\r\n376,49,90,Goal,1,8\r\n377,49,90,Assist,1,25\r\n378,50,63,Goal,2,38\r\n379,50,63,Assist,2,34\r\n380,50,72,Yellow Card,2,32\r\n381,50,78,Yellow Card,3,61\r\n382,51,32,Yellow Card,8,192\r\n383,51,32,Yellow Card,5,113\r\n384,51,46,Goal,8,199\r\n385,51,46,Assist,8,191\r\n386,51,57,Goal,8,191\r\n387,51,57,Assist,8,189\r\n388,51,76,Goal,5,128\r\n389,51,76,Assist,5,129\r\n390,51,87,Yellow Card,5,115\r\n391,52,29,Goal,6,149\r\n392,52,29,Assist,6,143\r\n393,52,34,Goal,6,157\r\n394,52,42,Goal,7,166\r\n395,52,42,Assist,7,164\r\n396,52,78,Yellow Card,7,176\r\n397,52,82,Goal,6,156\r\n398,52,82,Assist,6,133\r\n399,52,82,Yellow Card,6,156\r\n400,53,45,Goal,9,215\r\n401,53,45,Assist,9,216\r\n402,53,60,Goal,9,217\r\n403,53,60,Assist,9,216\r\n404,53,62,Yellow Card,9,221\r\n405,53,7,Goal,9,215\r\n406,53,7,Assist,9,234\r\n407,53,82,Yellow Card,9,225\r\n408,53,89,Yellow Card,12,297\r\n409,54,10,Goal,11,235\r\n410,54,39,Goal,10,236\r\n411,54,43,Goal,11,278\r\n412,54,45,Goal,10,245\r\n413,54,78,Goal,10,243\r\n414,54,79,Yellow Card,11,261\r\n415,54,80,Yellow Card,11,269\r\n416,54,89,Goal,10,250\r\n417,54,90,Yellow Card,11,281\r\n418,55,10,Goal,16,398\r\n419,55,10,Assist,16,416\r\n420,55,19,Yellow Card,13,326\r\n421,55,3,Goal,13,318\r\n422,55,3,Assist,13,326\r\n423,55,31,Goal,16,396\r\n424,55,31,Assist,16,403\r\n425,55,49,Goal,13,326\r\n426,55,90,Goal,16,412\r\n427,56,46,Yellow Card,15,386\r\n428,56,77,Yellow Card,14,346\r\n429,57,2,Goal,17,435\r\n430,57,2,Assist,17,433\r\n431,57,43,Yellow Card,20,497\r\n432,57,44,Yellow Card,17,421\r\n433,57,50,Yellow Card,20,515\r\n434,57,77,Goal,20,513\r\n435,57,77,Assist,20,517\r\n436,57,89,Yellow Card,20,513\r\n437,57,9,Goal,20,514\r\n438,57,9,Assist,20,509\r\n439,58,34,Yellow Card,19,487\r\n440,58,64,Goal,19,487\r\n441,58,7,Goal,19,487\r\n442,58,75,Yellow Card,18,449\r\n443,58,83,Yellow Card,18,461\r\n444,59,3,Goal,21,615\r\n445,59,54,Goal,24,607\r\n446,59,62,Goal,21,526\r\n447,59,7,Goal,21,539\r\n448,60,32,Yellow Card,23,576\r\n449,60,56,Goal,22,557\r\n450,60,62,Goal,23,583\r\n451,60,77,Yellow Card,22,549\r\n452,60,84,Yellow Card,23,589\r\n453,61,28,Goal,25,634\r\n454,61,46,Yellow Card,28,710\r\n455,61,50,Goal,25,634\r\n456,61,56,Yellow Card,28,713\r\n457,61,66,Goal,25,631\r\n458,61,84,Goal,28,713\r\n459,61,86,Goal,25,633\r\n460,61,90,Goal,25,646\r\n461,62,14,Goal,27,699\r\n462,62,19,Yellow Card,26,671\r\n463,62,19,Yellow Card,27,689\r\n464,62,41,Yellow Card,26,652\r\n465,62,43,Yellow Card,27,695\r\n466,62,5,Goal,26,671\r\n467,62,79,Yellow Card,27,682\r\n468,62,90,Yellow Card,26,667\r\n469,62,90,Yellow Card,27,680\r\n470,63,42,Goal,29,743\r\n471,63,42,Assist,29,733\r\n472,63,46,Yellow Card,29,743\r\n473,63,54,Yellow Card,32,831\r\n474,63,58,Yellow Card,32,819\r\n475,63,90,Yellow Card,32,813\r\n476,64,4,Yellow Card,31,792\r\n477,64,67,Yellow Card,31,786\r\n478,64,8,Yellow Card,30,778\r\n479,64,90,Yellow Card,31,789\r\n480,65,10,Yellow Card,36,916\r\n481,65,20,Goal,33,839\r\n482,65,20,Assist,33,842\r\n483,65,21,Goal,36,929\r\n484,65,21,Assist,36,931\r\n485,65,32,Goal,33,839\r\n486,65,32,Assist,33,840\r\n487,65,7,Goal,33,839\r\n488,65,7,Assist,33,842\r\n489,65,74,Yellow Card,33,840\r\n490,65,90,Goal,33,852\r\n491,65,90,Assist,33,844\r\n492,66,13,Red Card,35,886\r\n493,66,18,Yellow Card,34,862\r\n494,66,4,Goal,34,879\r\n495,66,4,Assist,34,862\r\n496,66,56,Goal,34,876\r\n497,66,56,Assist,34,866\r\n498,66,59,Goal,34,884\r\n499,66,59,Assist,34,876\r\n500,66,71,Goal,34,884\r\n501,66,71,Assist,34,871\r\n502,66,75,Yellow Card,35,900\r\n503,66,81,Yellow Card,34,884\r\n504,66,82,Goal,34,871\r\n505,66,82,Assist,34,884\r\n506,66,90,Yellow Card,35,907\r\n507,67,17,Yellow Card,40,1034\r\n508,67,19,Goal,37,947\r\n509,67,31,Goal,37,958\r\n510,67,55,Goal,40,1024\r\n511,67,55,Assist,40,1037\r\n512,67,64,Yellow Card,40,1019\r\n513,67,80,Goal,37,946\r\n514,67,90,Yellow Card,40,1021\r\n515,68,11,Yellow Card,39,995\r\n516,68,28,Goal,39,995\r\n517,68,28,Assist,39,996\r\n518,68,45,Goal,38,979\r\n519,68,45,Assist,38,969\r\n520,68,55,Goal,39,997\r\n521,68,55,Assist,39,994\r\n522,68,60,Goal,38,969\r\n523,68,60,Assist,38,970\r\n524,68,90,Goal,38,969\r\n525,68,90,Assist,38,970\r\n526,68,90,Goal,39,1002\r\n527,68,90,Assist,39,999\r\n528,69,86,Yellow Card,44,1132\r\n529,70,10,Goal,43,1106\r\n530,70,10,Assist,43,1098\r\n531,70,21,Yellow Card,42,1080\r\n532,70,43,Yellow Card,43,1094\r\n533,70,45,Yellow Card,42,1073\r\n534,70,47,Yellow Card,43,1105\r\n535,70,62,Yellow Card,42,1074\r\n536,70,68,Goal,42,1086\r\n537,70,78,Goal,42,1085\r\n538,70,90,Goal,42,1086\r\n539,70,90,Assist,42,1079\r\n540,71,53,Yellow Card,48,1239\r\n541,71,60,Yellow Card,45,1170\r\n542,71,62,Goal,45,1154\r\n543,71,62,Assist,45,1151\r\n544,71,67,Goal,45,1153\r\n545,71,67,Assist,45,1154\r\n546,71,83,Yellow Card,48,1238\r\n547,72,31,Goal,46,1187\r\n548,72,68,Yellow Card,46,1184\r\n549,72,73,Goal,47,1219\r\n550,72,73,Assist,47,1220\r\n551,72,83,Goal,46,1183\r\n552,72,83,Assist,46,1180\r\n553,72,90,Yellow Card,47,1217\r\n554,73,54,Yellow Card,5,129\r\n555,73,67,Yellow Card,5,127\r\n556,73,90,Goal,5,111\r\n557,74,12,Yellow Card,22,570\r\n558,74,14,Yellow Card,9,213\r\n559,74,29,Goal,22,570\r\n560,74,45,Yellow Card,22,561\r\n561,74,48,Yellow Card,9,221\r\n562,74,56,Goal,9,213\r\n563,74,56,Assist,9,211\r\n564,74,84,Yellow Card,22,571\r\n565,74,90,Goal,9,230\r\n566,74,90,Assist,9,216\r\n567,74,90,Yellow Card,9,216\r\n568,75,106,Yellow Card,17,423\r\n569,75,110,Yellow Card,17,418\r\n570,75,115,Yellow Card,17,426\r\n571,75,117,Yellow Card,14,361\r\n572,75,120,Yellow Card,14,344\r\n573,75,121,Penalty Shootout Miss,17,423\r\n574,75,121,Penalty Shootout Goal,14,349\r\n575,75,121,Penalty Shootout Goal,17,422\r\n576,75,121,Penalty Shootout Goal,14,353\r\n577,75,121,Penalty Shootout Goal,17,426\r\n578,75,121,Penalty Shootout Goal,14,361\r\n579,75,121,Penalty Shootout Miss,17,427\r\n580,75,121,Penalty Shootout Miss,14,347\r\n581,75,121,Penalty Shootout Goal,17,436\r\n582,75,121,Penalty Shootout Miss,14,343\r\n583,75,121,Penalty Shootout Miss,17,420\r\n584,75,121,Penalty Shootout Goal,14,351\r\n585,75,42,Goal,14,357\r\n586,75,42,Assist,14,361\r\n587,75,54,Goal,17,423\r\n588,75,54,Assist,17,433\r\n589,75,65,Yellow Card,14,352\r\n590,76,121,Penalty Shootout Goal,21,540\r\n591,76,121,Penalty Shootout Miss,10,258\r\n592,76,121,Penalty Shootout Miss,21,527\r\n593,76,121,Penalty Shootout Goal,10,243\r\n594,76,121,Penalty Shootout Goal,21,529\r\n595,76,121,Penalty Shootout Goal,10,241\r\n596,76,121,Penalty Shootout Miss,21,546\r\n597,76,121,Penalty Shootout Miss,10,236\r\n598,76,121,Penalty Shootout Miss,21,544\r\n599,76,121,Penalty Shootout Goal,10,245\r\n600,76,47,Yellow Card,10,248\r\n601,76,71,Yellow Card,21,525\r\n602,76,72,Goal,21,531\r\n603,76,72,Assist,21,544\r\n604,76,90,Goal,10,248\r\n605,76,90,Assist,10,241\r\n606,77,39,Goal,36,930\r\n607,77,45,Yellow Card,36,930\r\n608,77,74,Goal,19,483\r\n609,77,86,Goal,36,919\r\n610,77,86,Assist,36,916\r\n611,78,45,Goal,33,842\r\n612,78,53,Goal,33,844\r\n613,78,53,Assist,33,843\r\n614,78,74,Goal,33,842\r\n615,78,74,Assist,33,843\r\n616,79,22,Goal,1,16\r\n617,79,22,Assist,1,25\r\n618,79,31,Goal,1,9\r\n619,79,31,Assist,1,16\r\n620,79,45,Yellow Card,20,515\r\n621,79,90,Yellow Card,20,517\r\n622,79,90,Yellow Card,20,504\r\n623,79,95,Red Card,20,497\r\n624,80,19,Yellow Card,45,1154\r\n625,80,27,Yellow Card,42,1080\r\n626,80,7,Goal,42,1075\r\n627,80,75,Goal,45,1153\r\n628,80,75,Assist,45,1162\r\n629,80,86,Goal,45,1153\r\n630,80,86,Assist,45,1162\r\n631,81,120,Goal,25,632\r\n632,81,120,VAR Review,34,866\r\n633,81,25,Goal,34,879\r\n634,81,51,Goal,34,876\r\n635,81,51,Assist,34,877\r\n636,81,64,Yellow Card,25,628\r\n637,81,67,Yellow Card,34,866\r\n638,81,86,Goal,25,633\r\n639,81,86,Assist,25,639\r\n640,81,89,Goal,25,632\r\n641,81,89,Assist,25,634\r\n642,82,45,Goal,13,332\r\n643,82,45,Assist,13,329\r\n644,82,64,Red Card,13,332\r\n645,82,64,VAR Review,13,332\r\n646,82,80,Yellow Card,6,151\r\n647,82,82,Goal,13,329\r\n648,83,36,Goal,29,749\r\n649,83,36,Assist,29,752\r\n650,83,66,Goal,29,740\r\n651,83,66,Assist,29,743\r\n652,83,83,Yellow Card,39,993\r\n653,83,89,Goal,29,749\r\n654,83,89,Assist,29,752\r\n655,84,103,VAR Review,46,1174\r\n656,84,17,Yellow Card,41,1043\r\n657,84,53,Goal,46,1184\r\n658,84,53,Assist,46,1172\r\n659,84,59,Yellow Card,46,1180\r\n660,84,68,Goal,41,1047\r\n661,84,90,Goal,41,1049\r\n662,84,90,Assist,41,1057\r\n663,84,97,Yellow Card,46,1184\r\n664,85,10,Goal,8,189\r\n665,85,10,Assist,8,191\r\n666,85,36,Yellow Card,38,972\r\n667,85,46,Goal,8,193\r\n668,85,71,Yellow Card,38,976\r\n669,86,121,Penalty Shootout Miss,15,383\r\n670,86,121,Penalty Shootout Goal,26,671\r\n671,86,121,Penalty Shootout Goal,15,386\r\n672,86,121,Penalty Shootout Goal,26,655\r\n673,86,121,Penalty Shootout Goal,15,375\r\n674,86,121,Penalty Shootout Goal,26,660\r\n675,86,121,Penalty Shootout Miss,15,389\r\n676,86,121,Penalty Shootout Goal,26,654\r\n677,86,13,Goal,26,658\r\n678,86,55,Goal,15,653\r\n679,87,103,Goal,30,767\r\n680,87,111,Goal,37,757\r\n681,87,29,Goal,37,946\r\n682,87,59,Goal,30,768\r\n683,87,92,Goal,37,942\r\n684,88,14,Goal,44,1129\r\n685,88,14,Assist,44,1143\r\n686,89,70,Goal,33,842\r\n687,90,50,Goal,10,242\r\n688,90,50,Assist,10,236\r\n689,90,82,Goal,10,242\r\n690,90,82,Assist,10,244\r\n691,90,90,Goal,10,243\r\n692,90,90,Assist,10,244\r\n693,91,14,VAR Review,9,217\r\n694,91,3,VAR Review,36,916\r\n695,91,79,Goal,36,919\r\n696,91,79,Assist,36,931\r\n697,91,90,Goal,9,218\r\n698,91,90,Goal,36,919\r\n699,91,90+6,Yellow Card,9,218\r\n700,92,1,Yellow Card,45,1148\r\n701,92,36,Goal,45,1154\r\n702,92,36,Assist,45,1151\r\n703,92,38,Goal,45,1154\r\n704,92,38,Assist,45,1153\r\n705,92,42,Goal,1,16\r\n706,92,54,Red Card,45,1170\r\n707,92,54,VAR Review,45,1170\r\n708,92,60,Goal,45,1153\r\n709,92,68,Yellow Card,45,115

In [ ]:
import pandas as pd

teams = pd.read_csv("teams.csv")

In [ ]:
print(teams.head())

   team_id     team_name fifa_code group_letter confederation  \
0        1        Mexico       MEX            A      CONCACAF
1        2  South Africa       RSA            A           CAF
2        3   South Korea       KOR            A           AFC
3        4       Czechia       CZE            A          UEFA
4        5        Canada       CAN            B      CONCACAF

   fifa_ranking_pre_tournament  elo_rating     manager_name
0                           14        1810   Javier Aguirre
1                           60        1620       Hugo Broos
2                           22        1800    Hong Myung-bo
3                           40        1740  Miroslav Koubek
4                           33        1795     Jesse Marsch

In [ ]:
matches = pd.read_csv("matches.csv")
matches_detailed = pd.read_csv("matches_detailed.csv")
events = pd.read_csv("match_events.csv")
lineups = pd.read_csv("match_lineups.csv")
team_stats = pd.read_csv("match_team_stats.csv")
players = pd.read_csv("player_stats.csv")
squads = pd.read_csv("squads_and_players.csv")
teams = pd.read_csv("teams.csv")
venues = pd.read_csv("venues.csv")
stages = pd.read_csv("tournament_stages.csv")
referees = pd.read_csv("referees.csv")

In [ ]:
print(teams.head())
print(matches.head())
print(events.head())
print(matches_detailed.head())
print(team_stats.head())
print(squads.head())
print(venues.head())
print(stages.head())

   team_id     team_name fifa_code group_letter confederation  \
0        1        Mexico       MEX            A      CONCACAF
1        2  South Africa       RSA            A           CAF
2        3   South Korea       KOR            A           AFC
3        4       Czechia       CZE            A          UEFA
4        5        Canada       CAN            B      CONCACAF

   fifa_ranking_pre_tournament  elo_rating     manager_name
0                           14        1810   Javier Aguirre
1                           60        1620       Hugo Broos
2                           22        1800    Hong Myung-bo
3                           40        1740  Miroslav Koubek
4                           33        1795     Jesse Marsch
   match_id        date kickoff_time_utc  stage_id  venue_id  home_team_id  \
0         1  2026-06-11            19:00         1         1             1
1         2  2026-06-11            23:00         1         7             3
2         3  2026-06-12            19:00         1         6             5
3         4  2026-06-12            23:00         1         3            13
4         5  2026-06-13            15:00         1        10             7

   away_team_id  home_score  away_score  home_penalty_score  \
0             2           2           0                 NaN
1             4           2           1                 NaN
2             6           1           1                 NaN
3            14           4           1                 NaN
4             8           1           1                 NaN

   away_penalty_score     status result_type  home_xg  away_xg  referee_id  \
0                 NaN  Completed     Regular     1.84     0.52           1
1                 NaN  Completed     Regular     1.45     1.12           2
2                 NaN  Completed     Regular     1.35     0.98           3
3                 NaN  Completed     Regular     2.76     0.88           4
4                 NaN  Completed     Regular     0.78     1.54           5

   player_of_the_match_id
0                      16
1                      58
2                     112
3                     332
4                     157
   event_id  match_id minute   event_type  team_id  player_id
0         1         1     17  Yellow Card        2         30
1         2         1     23  Yellow Card        1         26
2         3         1     55     Red Card        2         39
3         4         1     55   VAR Review        2         39
4         5         1     67         Goal        1          9
   match_id        date kickoff_time_utc   stage_name  \
0         1  2026-06-11            19:00  Group Stage
1         2  2026-06-11            23:00  Group Stage
2         3  2026-06-12            19:00  Group Stage
3         4  2026-06-12            23:00  Group Stage
4         5  2026-06-13            15:00  Group Stage

                           stadium_name         city country home_team_name  \
0  Mexico City Stadium (Estadio Azteca)  Mexico City     MEX         Mexico
1   Guadalajara Stadium (Estadio Akron)      Zapopan     MEX    South Korea
2           Toronto Stadium (BMO Field)      Toronto     CAN         Canada
3    Los Angeles Stadium (SoFi Stadium)    Inglewood     USA            USA
4     Boston Stadium (Gillette Stadium)   Foxborough     USA          Qatar

  home_fifa_code          away_team_name  ... home_penalty_score  \
0            MEX            South Africa  ...                NaN
1            KOR                 Czechia  ...                NaN
2            CAN  Bosnia and Herzegovina  ...                NaN
3            USA                Paraguay  ...                NaN
4            QAT             Switzerland  ...                NaN

   away_penalty_score     status  result_type  home_xg away_xg  \
0                 NaN  Completed      Regular     1.84    0.52
1                 NaN  Completed      Regular     1.45    1.12
2                 NaN  Completed      Regular     1.35    0.98
3                 NaN  Completed      Regular     2.76    0.88
4                 NaN  Completed      Regular     0.78    1.54

               home_goalkeeper         away_goalkeeper  \
0             José Raúl Rangel  Ronwen Hayden Williams
1                 Seunggyu Kim           Mat ě j Kovar
2               Maxime Crepeau           Nikola Vasilj
3  Matthew Andrew Geary Freese     Orlando Daniel Gill
4      Ibrahim Mahmoud Abunada            Gregor Kobel

     player_of_the_match_name      referee_name
0      Julián Andrés Quinones  Szymon Marciniak
1                Inbeom Hwang    Daniele Orsato
2  Ismaël Kenneth Jordan Kone    Michael Oliver
3   Folarin Jolaoluwa Balogun    Anthony Taylor
4     Ibrahim Mahmoud Abunada    Clément Turpin

[5 rows x 23 columns]
   match_id  team_id  possession_pct  total_shots  shots_on_target  corners  \
0         1        1              57           16                4        6
1         1        2              43            3                2        3
2         2        3              54           12                5        4
3         2        4              46           10                3        3
4         3        5              52           13                4        9

   fouls  offsides  saves         player_of_the_match    data_source  \
0     11         2      1      Julián Andrés Quinones       fifa.com
1     15         1      4                         NaN       fifa.com
2     10         1      2                Inbeom Hwang  sofascore.com
3     13         2      4                         NaN  sofascore.com
4     12         2      3  Ismaël Kenneth Jordan Kone       fifa.com

  last_updated
0   2026-06-24
1   2026-06-24
2   2026-06-24
3   2026-06-24
4   2026-06-24
   player_id  team_id            player_name position            club_team  \
0          1        1       José Raúl Rangel       GK       CD Guadalajara
1          2        1  Jorge Eduardo Sanchez      DEF        PAOK Saloniki
2          3        1     César Jasib Montes      DEF  FC Lokomotiv Moscow
3          4        1     Edson Omar Alvarez      DEF        Fenerbahçe SK
4          5        1   Johan Felipe Vasquez      DEF            Genoa CFC

   market_value_eur  caps date_of_birth  height_cm  goals
0           8933646    15    2000-02-25        190      0
1          24628639    59    1997-12-10        176      3
2          10912552    69    1997-02-24        191      4
3          10875943   100    1997-10-24        180      7
4          18265363    47    1998-10-22        182      3
   venue_id                                   stadium_name             city  \
0         1           Mexico City Stadium (Estadio Azteca)      Mexico City
1         2  New York New Jersey Stadium (MetLife Stadium)  East Rutherford
2         3             Los Angeles Stadium (SoFi Stadium)        Inglewood
3         4                  Dallas Stadium (AT&T Stadium)        Arlington
4         5                   Vancouver Stadium (BC Place)        Vancouver

  country  capacity  latitude  longitude  elevation_meters
0     MEX     80824   19.3031   -99.1506              2200
1     USA     82500   40.8136   -74.0744                 7
2     USA     70240   33.9535  -118.3390                30
3     USA     80000   32.7473   -97.0928               184
4     CAN     54500   49.2768  -123.1120                 9
   stage_id      stage_name  is_knockout
0         1     Group Stage        False
1         2     Round of 32         True
2         3     Round of 16         True
3         4  Quarter-finals         True
4         5     Semi-finals         True

In [ ]:
print(venues.head())

   venue_id                                   stadium_name             city  \
0         1           Mexico City Stadium (Estadio Azteca)      Mexico City
1         2  New York New Jersey Stadium (MetLife Stadium)  East Rutherford
2         3             Los Angeles Stadium (SoFi Stadium)        Inglewood
3         4                  Dallas Stadium (AT&T Stadium)        Arlington
4         5                   Vancouver Stadium (BC Place)        Vancouver

  country  capacity  latitude  longitude  elevation_meters
0     MEX     80824   19.3031   -99.1506              2200
1     USA     82500   40.8136   -74.0744                 7
2     USA     70240   33.9535  -118.3390                30
3     USA     80000   32.7473   -97.0928               184
4     CAN     54500   49.2768  -123.1120                 9

In [ ]:
print(events.head())

   event_id  match_id minute   event_type  team_id  player_id
0         1         1      9         Goal        1         16
1         2         1      9       Assist        1          6
2         3         1     17  Yellow Card        2         30
3         4         1     23  Yellow Card        1         26
4         5         1     55     Red Card        2         39

In [ ]:
"""
matches
matches_detailed
events
lineups
team_stats
players
squads
teams
venues
stages
referees
"""

In [ ]:
matches.duplicated().sum()
matches_detailed.duplicated().sum()
events.duplicated().sum()
lineups.duplicated().sum()
team_stats.duplicated().sum()
players.duplicated().sum()
squads.duplicated().sum()
teams.duplicated().sum()
venues.duplicated().sum()
stages.duplicated().sum()
referees.duplicated().sum()

np.int64(0)

In [ ]:
matches.duplicated().info()
matches_detailed.duplicated().info()
events.duplicated().info()
lineups.duplicated().info()
team_stats.duplicated().info()
players.duplicated().info()
squads.duplicated().info()
teams.duplicated().info()
venues.duplicated().info()
stages.duplicated().info()
referees.duplicated().info()

<class 'pandas.core.series.Series'>
RangeIndex: 104 entries, 0 to 103
Series name: None
Non-Null Count  Dtype
--------------  -----
104 non-null    bool
dtypes: bool(1)
memory usage: 236.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 104 entries, 0 to 103
Series name: None
Non-Null Count  Dtype
--------------  -----
104 non-null    bool
dtypes: bool(1)
memory usage: 236.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 834 entries, 0 to 833
Series name: None
Non-Null Count  Dtype
--------------  -----
834 non-null    bool
dtypes: bool(1)
memory usage: 966.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 5408 entries, 0 to 5407
Series name: None
Non-Null Count  Dtype
--------------  -----
5408 non-null   bool
dtypes: bool(1)
memory usage: 5.4 KB
<class 'pandas.core.series.Series'>
RangeIndex: 208 entries, 0 to 207
Series name: None
Non-Null Count  Dtype
--------------  -----
208 non-null    bool
dtypes: bool(1)
memory usage: 340.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 1248 entries, 0 to 1247
Series name: None
Non-Null Count  Dtype
--------------  -----
1248 non-null   bool
dtypes: bool(1)
memory usage: 1.3 KB
<class 'pandas.core.series.Series'>
RangeIndex: 1248 entries, 0 to 1247
Series name: None
Non-Null Count  Dtype
--------------  -----
1248 non-null   bool
dtypes: bool(1)
memory usage: 1.3 KB
<class 'pandas.core.series.Series'>
RangeIndex: 48 entries, 0 to 47
Series name: None
Non-Null Count  Dtype
--------------  -----
48 non-null     bool
dtypes: bool(1)
memory usage: 180.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 16 entries, 0 to 15
Series name: None
Non-Null Count  Dtype
--------------  -----
16 non-null     bool
dtypes: bool(1)
memory usage: 148.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 7 entries, 0 to 6
Series name: None
Non-Null Count  Dtype
--------------  -----
7 non-null      bool
dtypes: bool(1)
memory usage: 139.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 28 entries, 0 to 27
Series name: None
Non-Null Count  Dtype
--------------  -----
28 non-null     bool
dtypes: bool(1)
memory usage: 160.0 bytes

In [ ]:
matches.duplicated().describe()

count       104
unique        1
top       False
freq        104
dtype: object

In [ ]:
matches.describe()

,match_id,stage_id,venue_id,home_team_id,away_team_id,home_score,away_score,home_penalty_score,away_penalty_score,home_xg,away_xg,referee_id,player_of_the_match_id
count,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,4.000000,4.00000,104.000000,104.000000,104.000000,104.000000
mean,52.500000,1.605769,8.605769,24.288462,25.826923,1.721154,1.240385,2.750000,3.50000,1.545769,1.108077,9.884615,633.701923
std,30.166206,1.161003,4.829960,13.981036,13.758981,1.503761,1.234576,0.957427,0.57735,0.924910,0.720078,6.499153,358.211086
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,2.000000,3.00000,0.130000,0.080000,1.000000,7.000000
25%,26.750000,1.000000,4.000000,12.750000,14.000000,1.000000,0.000000,2.000000,3.00000,0.780000,0.547500,5.000000,331.250000
50%,52.500000,1.000000,9.000000,25.000000,26.000000,1.000000,1.000000,2.500000,3.50000,1.450000,0.960000,9.000000,668.500000
75%,78.250000,2.000000,13.000000,36.250000,37.250000,3.000000,2.000000,3.250000,4.00000,2.090000,1.480000,14.000000,946.000000
max,104.000000,7.000000,16.000000,48.000000,48.000000,7.000000,6.000000,4.000000,4.00000,4.820000,3.580000,28.000000,1207.000000

In [ ]:
matches_detailed.describe()

,match_id,home_score,away_score,home_penalty_score,away_penalty_score,home_xg,away_xg
count,104.000000,104.000000,104.000000,4.000000,4.00000,104.000000,104.000000
mean,52.500000,1.721154,1.240385,2.750000,3.50000,1.545769,1.108077
std,30.166206,1.503761,1.234576,0.957427,0.57735,0.924910,0.720078
min,1.000000,0.000000,0.000000,2.000000,3.00000,0.130000,0.080000
25%,26.750000,1.000000,0.000000,2.000000,3.00000,0.780000,0.547500
50%,52.500000,1.000000,1.000000,2.500000,3.50000,1.450000,0.960000
75%,78.250000,3.000000,2.000000,3.250000,4.00000,2.090000,1.480000
max,104.000000,7.000000,6.000000,4.000000,4.00000,4.820000,3.580000

In [ ]:
all = [matches,
matches_detailed,
events,
lineups,
team_stats,
players,
squads,
teams,
venues,
stages,
referees]

In [ ]:
for i, df in enumerate(all, start=1):
    print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                104 non-null    int64
 1   date                    104 non-null    object
 2   kickoff_time_utc        104 non-null    object
 3   stage_id                104 non-null    int64
 4   venue_id                104 non-null    int64
 5   home_team_id            104 non-null    int64
 6   away_team_id            104 non-null    int64
 7   home_score              104 non-null    int64
 8   away_score              104 non-null    int64
 9   home_penalty_score      4 non-null      float64
 10  away_penalty_score      4 non-null      float64
 11  status                  104 non-null    object
 12  result_type             104 non-null    object
 13  home_xg                 104 non-null    float64
 14  away_xg                 104 non-null    float64
 15  referee_id              104 non-null    int64
 16  player_of_the_match_id  104 non-null    int64
dtypes: float64(4), int64(9), object(4)
memory usage: 13.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   match_id                  104 non-null    int64
 1   date                      104 non-null    object
 2   kickoff_time_utc          104 non-null    object
 3   stage_name                104 non-null    object
 4   stadium_name              104 non-null    object
 5   city                      104 non-null    object
 6   country                   104 non-null    object
 7   home_team_name            104 non-null    object
 8   home_fifa_code            104 non-null    object
 9   away_team_name            104 non-null    object
 10  away_fifa_code            104 non-null    object
 11  home_score                104 non-null    int64
 12  away_score                104 non-null    int64
 13  home_penalty_score        4 non-null      float64
 14  away_penalty_score        4 non-null      float64
 15  status                    104 non-null    object
 16  result_type               104 non-null    object
 17  home_xg                   104 non-null    float64
 18  away_xg                   104 non-null    float64
 19  home_goalkeeper           104 non-null    object
 20  away_goalkeeper           104 non-null    object
 21  player_of_the_match_name  104 non-null    object
 22  referee_name              104 non-null    object
dtypes: float64(4), int64(3), object(16)
memory usage: 18.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 834 entries, 0 to 833
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   event_id    834 non-null    int64
 1   match_id    834 non-null    int64
 2   minute      834 non-null    object
 3   event_type  834 non-null    object
 4   team_id     834 non-null    int64
 5   player_id   834 non-null    int64
dtypes: int64(4), object(2)
memory usage: 39.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5408 entries, 0 to 5407
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lineup_id          5408 non-null   int64
 1   match_id           5408 non-null   int64
 2   player_id          5408 non-null   int64
 3   team_id            5408 non-null   int64
 4   is_starting_xi     5408 non-null   int64
 5   tactical_position  5408 non-null   object
 6   minutes_played     5408 non-null   int64
dtypes: int64(6), object(1)
memory usage: 295.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             208 non-null    int64
 1   team_id              208 non-null    int64
 2   possession_pct       208 non-null    int64
 3   total_shots          208 non-null    int64
 4   shots_on_target      208 non-null    int64
 5   corners              208 non-null    int64
 6   fouls                208 non-null    int64
 7   offsides             208 non-null    int64
 8   saves                208 non-null    int64
 9   player_of_the_match  105 non-null    object
 10  data_source          208 non-null    object
 11  last_updated         208 non-null    object
dtypes: int64(9), object(3)
memory usage: 19.6+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   player_id        1248 non-null   int64
 1   player_name      1248 non-null   object
 2   team_id          1248 non-null   int64
 3   position         1248 non-null   object
 4   matches_played   1248 non-null   int64
 5   matches_started  1248 non-null   int64
 6   minutes_played   1248 non-null   int64
 7   goals            1248 non-null   int64
 8   assists          1248 non-null   int64
 9   shots            0 non-null      float64
 10  shots_on_target  0 non-null      float64
 11  yellow_cards     1248 non-null   int64
 12  red_cards        1248 non-null   int64
 13  penalty_goals    1248 non-null   int64
 14  own_goals        1248 non-null   int64
 15  clean_sheets     145 non-null    float64
 16  saves            145 non-null    float64
 17  goals_conceded   145 non-null    float64
 18  average_rating   0 non-null      float64
 19  data_source      1035 non-null   object
 20  last_verified    1248 non-null   object
dtypes: float64(6), int64(11), object(4)
memory usage: 204.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         1248 non-null   int64
 1   team_id           1248 non-null   int64
 2   player_name       1248 non-null   object
 3   position          1248 non-null   object
 4   club_team         1248 non-null   object
 5   market_value_eur  1248 non-null   int64
 6   caps              1248 non-null   int64
 7   date_of_birth     1248 non-null   object
 8   height_cm         1248 non-null   int64
 9   goals             1248 non-null   int64
dtypes: int64(6), object(4)
memory usage: 97.6+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   team_id                      48 non-null     int64
 1   team_name                    48 non-null     object
 2   fifa_code                    48 non-null     object
 3   group_letter                 48 non-null     object
 4   confederation                48 non-null     object
 5   fifa_ranking_pre_tournament  48 non-null     int64
 6   elo_rating                   48 non-null     int64
 7   manager_name                 48 non-null     object
dtypes: int64(3), object(5)
memory usage: 3.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   venue_id          16 non-null     int64
 1   stadium_name      16 non-null     object
 2   city              16 non-null     object
 3   country           16 non-null     object
 4   capacity          16 non-null     int64
 5   latitude          16 non-null     float64
 6   longitude         16 non-null     float64
 7   elevation_meters  16 non-null     int64
dtypes: float64(2), int64(3), object(3)
memory usage: 1.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stage_id     7 non-null      int64
 1   stage_name   7 non-null      object
 2   is_knockout  7 non-null      bool
dtypes: bool(1), int64(1), object(1)
memory usage: 251.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   referee_id          28 non-null     int64
 1   name                28 non-null     object
 2   country             28 non-null     object
 3   avg_cards_per_game  28 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.0+ KB
None

In [ ]:

for i, df in enumerate(all, start=1):
      print(df.isna().sum()
)

match_id                    0
date                        0
kickoff_time_utc            0
stage_id                    0
venue_id                    0
home_team_id                0
away_team_id                0
home_score                  0
away_score                  0
home_penalty_score        100
away_penalty_score        100
status                      0
result_type                 0
home_xg                     0
away_xg                     0
referee_id                  0
player_of_the_match_id      0
dtype: int64
match_id                      0
date                          0
kickoff_time_utc              0
stage_name                    0
stadium_name                  0
city                          0
country                       0
home_team_name                0
home_fifa_code                0
away_team_name                0
away_fifa_code                0
home_score                    0
away_score                    0
home_penalty_score          100
away_penalty_score          100
status                        0
result_type                   0
home_xg                       0
away_xg                       0
home_goalkeeper               0
away_goalkeeper               0
player_of_the_match_name      0
referee_name                  0
dtype: int64
event_id      0
match_id      0
minute        0
event_type    0
team_id       0
player_id     0
dtype: int64
lineup_id            0
match_id             0
player_id            0
team_id              0
is_starting_xi       0
tactical_position    0
minutes_played       0
dtype: int64
match_id                 0
team_id                  0
possession_pct           0
total_shots              0
shots_on_target          0
corners                  0
fouls                    0
offsides                 0
saves                    0
player_of_the_match    103
data_source              0
last_updated             0
dtype: int64
player_id             0
player_name           0
team_id               0
position              0
matches_played        0
matches_started       0
minutes_played        0
goals                 0
assists               0
shots              1248
shots_on_target    1248
yellow_cards          0
red_cards             0
penalty_goals         0
own_goals             0
clean_sheets       1103
saves              1103
goals_conceded     1103
average_rating     1248
data_source         213
last_verified         0
dtype: int64
player_id           0
team_id             0
player_name         0
position            0
club_team           0
market_value_eur    0
caps                0
date_of_birth       0
height_cm           0
goals               0
dtype: int64
team_id                        0
team_name                      0
fifa_code                      0
group_letter                   0
confederation                  0
fifa_ranking_pre_tournament    0
elo_rating                     0
manager_name                   0
dtype: int64
venue_id            0
stadium_name        0
city                0
country             0
capacity            0
latitude            0
longitude           0
elevation_meters    0
dtype: int64
stage_id       0
stage_name     0
is_knockout    0
dtype: int64
referee_id            0
name                  0
country               0
avg_cards_per_game    0
dtype: int64

In [ ]:
dfs = {"matches":matches,
"matches_detailed":matches_detailed,
"events":events,
"lineups":lineups,
"team_stats":team_stats,
"players":players,
"squads":squads,
"teams":teams,
"venues":venues,
"stages":stages,
"referees":referees,}

for name, df in dfs.items():
    print(f"\n{name}:")
    print(df.select_dtypes(include=["object"]).columns.tolist())

matches:
['date', 'kickoff_time_utc', 'status', 'result_type']

matches_detailed:
['date', 'kickoff_time_utc', 'stage_name', 'stadium_name', 'city', 'country', 'home_team_name', 'home_fifa_code', 'away_team_name', 'away_fifa_code', 'status', 'result_type', 'home_goalkeeper', 'away_goalkeeper', 'player_of_the_match_name', 'referee_name']

events:
['minute', 'event_type']

lineups:
['tactical_position']

team_stats:
['player_of_the_match', 'data_source', 'last_updated']

players:
['player_name', 'position', 'data_source', 'last_verified']

squads:
['player_name', 'position', 'club_team', 'date_of_birth']

teams:
['team_name', 'fifa_code', 'group_letter', 'confederation', 'manager_name']

venues:
['stadium_name', 'city', 'country']

stages:
['stage_name']

referees:
['name', 'country']

In [ ]:
for df_name, df in dfs.items():
    print(f"\n===== {df_name} =====")

    object_columns = df.select_dtypes(include=["object"]).columns

    for col in object_columns:
        print(f"\nKolumna: {col}")
        print(df[col].unique())

===== matches =====

Kolumna: date
['2026-06-11' '2026-06-12' '2026-06-13' '2026-06-14' '2026-06-15'
 '2026-06-16' '2026-06-17' '2026-06-18' '2026-06-19' '2026-06-20'
 '2026-06-21' '2026-06-22' '2026-06-23' '2026-06-24' '2026-06-25'
 '2026-06-26' '2026-06-27' '2026-06-28' '2026-06-29' '2026-06-30'
 '2026-07-01' '2026-07-02' '2026-07-03' '2026-07-04' '2026-07-05'
 '2026-07-06' '2026-07-07' '2026-07-09' '2026-07-10' '2026-07-11'
 '2026-07-12' '2026-07-14' '2026-07-15' '2026-07-18' '2026-07-19']

Kolumna: kickoff_time_utc
['19:00' '23:00' '15:00' '18:00' '21:00' '23:59' '22:00' '12:00' '02:30'
 '07:00' '03:00' '02:00' '06:00' '01:00' '05:00' '09:00' '00:00' '04:00'
 '07:30' '20:00' '16:00']

Kolumna: status
['Completed']

Kolumna: result_type
['Regular' 'Penalties' 'AET']

===== matches_detailed =====

Kolumna: date
['2026-06-11' '2026-06-12' '2026-06-13' '2026-06-14' '2026-06-15'
 '2026-06-16' '2026-06-17' '2026-06-18' '2026-06-19' '2026-06-20'
 '2026-06-21' '2026-06-22' '2026-06-23' '2026-06-24' '2026-06-25'
 '2026-06-26' '2026-06-27' '2026-06-28' '2026-06-29' '2026-06-30'
 '2026-07-01' '2026-07-02' '2026-07-03' '2026-07-04' '2026-07-05'
 '2026-07-06' '2026-07-07' '2026-07-09' '2026-07-10' '2026-07-11'
 '2026-07-12' '2026-07-14' '2026-07-15' '2026-07-18' '2026-07-19']

Kolumna: kickoff_time_utc
['19:00' '23:00' '15:00' '18:00' '21:00' '23:59' '22:00' '12:00' '02:30'
 '07:00' '03:00' '02:00' '06:00' '01:00' '05:00' '09:00' '00:00' '04:00'
 '07:30' '20:00' '16:00']

Kolumna: stage_name
['Group Stage' 'Round of 32' 'Round of 16' 'Quarter-finals' 'Semi-finals'
 'Third-place match' 'Final']

Kolumna: stadium_name
['Mexico City Stadium (Estadio Azteca)'
 'Guadalajara Stadium (Estadio Akron)' 'Toronto Stadium (BMO Field)'
 'Los Angeles Stadium (SoFi Stadium)' 'Boston Stadium (Gillette Stadium)'
 'New York New Jersey Stadium (MetLife Stadium)'
 'Philadelphia Stadium (Lincoln Financial Field)'
 'Seattle Stadium (Lumen Field)' 'Atlanta Stadium (Mercedes-Benz Stadium)'
 "San Francisco Bay Area Stadium (Levi's Stadium)"
 'Houston Stadium (NRG Stadium)' 'Kansas City Stadium (Arrowhead Stadium)'
 'Miami Stadium (Hard Rock Stadium)' 'Dallas Stadium (AT&T Stadium)'
 'Monterrey Stadium (Estadio BBVA)' 'Vancouver Stadium (BC Place)']

Kolumna: city
['Mexico City' 'Zapopan' 'Toronto' 'Inglewood' 'Foxborough'
 'East Rutherford' 'Philadelphia' 'Seattle' 'Atlanta' 'Santa Clara'
 'Houston' 'Kansas City' 'Miami Gardens' 'Arlington' 'Guadalupe'
 'Vancouver']

Kolumna: country
['MEX' 'CAN' 'USA']

Kolumna: home_team_name
['Mexico' 'South Korea' 'Canada' 'USA' 'Qatar' 'Brazil' 'Haiti'
 'Australia' 'Germany' 'Netherlands' "Côte d'Ivoire" 'Sweden' 'Spain'
 'Belgium' 'Saudi Arabia' 'IR Iran' 'France' 'Iraq' 'Argentina' 'Austria'
 'Portugal' 'England' 'Ghana' 'Uzbekistan' 'Czechia' 'Switzerland'
 'Scotland' 'Türkiye' 'Ecuador' 'Tunisia' 'New Zealand' 'Uruguay' 'Norway'
 'Jordan' 'Colombia' 'Panama' 'South Africa' 'Bosnia and Herzegovina'
 'Morocco' 'Paraguay' 'Curaçao' 'Japan' 'Egypt' 'Cabo Verde' 'Senegal'
 'Algeria' 'Congo DR' 'Croatia']

Kolumna: home_fifa_code
['MEX' 'KOR' 'CAN' 'USA' 'QAT' 'BRA' 'HAI' 'AUS' 'GER' 'NED' 'CIV' 'SWE'
 'ESP' 'BEL' 'KSA' 'IRN' 'FRA' 'IRQ' 'ARG' 'AUT' 'POR' 'ENG' 'GHA' 'UZB'
 'CZE' 'SUI' 'SCO' 'TUR' 'ECU' 'TUN' 'NZL' 'URU' 'NOR' 'JOR' 'COL' 'PAN'
 'RSA' 'BIH' 'MAR' 'PAR' 'CUW' 'JPN' 'EGY' 'CPV' 'SEN' 'ALG' 'COD' 'CRO']

Kolumna: away_team_name
['South Africa' 'Czechia' 'Bosnia and Herzegovina' 'Paraguay'
 'Switzerland' 'Morocco' 'Scotland' 'Türkiye' 'Curaçao' 'Japan' 'Ecuador'
 'Tunisia' 'Cabo Verde' 'Egypt' 'Uruguay' 'New Zealand' 'Senegal' 'Norway'
 'Algeria' 'Jordan' 'Congo DR' 'Croatia' 'Panama' 'Colombia' 'South Korea'
 'Qatar' 'Haiti' 'Australia' "Côte d'Ivoire" 'Sweden' 'IR Iran'
 'Saudi Arabia' 'Iraq' 'Austria' 'Uzbekistan' 'Ghana' 'Mexico' 'Canada'
 'Brazil' 'USA' 'Germany' 'Netherlands' 'Belgium' 'Spain' 'France'
 'Argentina' 'Portugal' 'England']

Kolumna: away_fifa_code
['RSA' 'CZE' 'BIH' 'PAR' 'SUI' 'MAR' 'SCO' 'TUR' 'CUW' 'JPN' 'ECU' 'TUN'
 'CPV' 'EGY' 'URU' 'NZL' 'SEN' 'NOR' 'ALG' 'JOR' 'COD' 'CRO' 'PAN' 'COL'
 'KOR' 'QAT' 'HAI' 'AUS' 'CIV' 'SWE' 'IRN' 'KSA' 'IRQ' 'AUT' 'UZB' 'GHA'
 'MEX' 'CAN' 'BRA' 'USA' 'GER' 'NED' 'BEL' 'ESP' 'FRA' 'ARG' 'POR' 'ENG']

Kolumna: status
['Completed']

Kolumna: result_type
['Regular' 'Penalties' 'AET']

Kolumna: home_goalkeeper
['José Raúl Rangel' 'Seunggyu Kim' 'Maxime Crepeau'
 'Matthew Andrew Geary Freese' 'Ibrahim Mahmoud Abunada' 'Ramsés Alisson'
 'Johny Placide' 'Patrick Thomas Beach' 'Manuel Peter Neuer'
 'Bart Verbruggen' 'Yahia Fofana' 'Bo Kristoffer Nordfeldt' 'Unai Simon'
 'Thibaut Nicolas Courtois' 'Khalil Mohammed Alowais'
 'Ali Reza Beiranvand' 'Mike Peterson Maignan' 'Hasan Hachim Jalal Hassan'
 'Damián Emiliano Martinez' 'Alexander Schlager' 'Diogo Diogo Costa'
 'Jordan Lee Pickford' 'Lawrence Ati Zigi' 'Utkir Yusupov' 'Mat ě j Kovar'
 'Gregor Kobel' 'Angus Fraser James Gunn' 'Ugurcan Cakir'
 'Hernán Ismael Galindez' 'Aymen Dahmen' 'Maxime Teremoana Crocombe'
 'Nestor Fernando Muslera' 'Ørjan Haskjold Nyland'
 "Mo'ien Hasan Yazeed Abulaila" 'Camilo Andres Vargas' 'Orlando Mosquera'
 'Ronwen Hayden Williams' 'Nikola Vasilj' 'Yassine Bounou'
 'Orlando Daniel Gill' 'Eloy Victor Room' 'Zion Suzuki'
 'Abdelaziz Mohame Mostafa' 'José Vozinha' 'Egil Selvik' 'Mory Diaw'
 "Ra'ed Mahmoud Abdallah Alfakhori" 'Oussama Benbot' 'Lionel Nzau Mpasi'
 'Dominik Livakovic' 'Unai Simón']

Kolumna: away_goalkeeper
['Ronwen Hayden Williams' 'Mat ě j Kovar' 'Nikola Vasilj'
 'Orlando Daniel Gill' 'Gregor Kobel' 'Yassine Bounou'
 'Angus Fraser James Gunn' 'Ugurcan Cakir' 'Eloy Victor Room'
 'Zion Suzuki' 'Hernán Ismael Galindez' 'Abdelmouhib Chamakh'
 'José Vozinha' 'Abdelaziz Mohame Mostafa' 'Nestor Fernando Muslera'
 'Maxime Teremoana Crocombe' 'Edouard Osoque Mendy'
 'Ørjan Haskjold Nyland' 'Luca Zinedine Zidane'
 "Ra'ed Mahmoud Abdallah Alfakhori" 'Lionel Nzau Mpasi'
 'Dominik Livakovic' 'Orlando Mosquera' 'Camilo Andres Vargas'
 'Seunggyu Kim' 'Ibrahim Mahmoud Abunada' 'Johny Placide'
 'Patrick Thomas Beach' 'Yahia Fofana' 'Bo Kristoffer Nordfeldt'
 'Ali Reza Beiranvand' 'Khalil Mohammed Alowais' 'Basil Fadhil Ahmed'
 'Alexander Schlager' 'Abduvakhid Nematov' 'Benjamin Asare'
 'José Raúl Rangel' 'Maxime Crepeau' 'Ramsés Alisson'
 'Matthew Charles Turner' 'Manuel Peter Neuer' 'Bart Verbruggen'
 'Jacob Mikael Widell Zetterstrom' 'Thibaut Nicolas Courtois' 'Unai Simon'
 'Mike Peterson Maignan' 'Damián Emiliano Martinez' 'Diogo Diogo Costa'
 'Jordan Lee Pickford' 'Mory Diaw' 'Lawrence Ati Zigi'
 'Dean Bradley Henderson' 'Damián Emiliano Martínez']

Kolumna: player_of_the_match_name
['Julián Andrés Quinones' 'Inbeom Hwang' 'Ismaël Kenneth Jordan Kone'
 'Folarin Jolaoluwa Balogun' 'Ibrahim Mahmoud Abunada' 'José Vinicius'
 'Mc' 'Nestory Irankunda' 'Kai Lukas Havertz' 'Virgil Van Dijk'
 'Yan Diomande' 'Alexander Isak' 'José Vozinha' 'Ashour Metwaly Emam'
 'Khalil Mohammed Alowais' 'Ramin Rezaeian' 'Michael Akpovie Olise'
 'Erling Braut Haaland' 'Lionel Andrés Messi' 'Iyad Ali Ali Olwan'
 'Pedro Joao Neves' 'Harry Edward Kane' 'Antoine Serlom Semenyo'
 'Luis Fernando Diaz' 'Luis Francisco Romo' 'Michal Sadilek'
 'Jonathan Christian David' 'Johan Kula Manzambi' 'Matheus Matheus Cunha'
 'Ismael Saibari' 'Matias Galarza' 'Deniz Undav' 'Eloy Victor Room'
 'Cody Mathès Gakpo' 'Ayase Ueda' 'Ali Reza Beiranvand'
 'Hamed Mahrous Mohamed Salah' 'Mikel Oyarzabal' 'Kylian Mbappe'
 'Ibrahim Maza' 'Ronaldo Cristiano Ronaldo' 'Daniel Munoz' 'Nico Oreilly'
 'Ante Budimir' 'Mateo Chavez' 'Thapelo Maseko' 'Kerim Alajbegovic'
 'Achraf Hakimi' 'Arda Guler' 'Roberto Junior Fernandez'
 'Nilson David Angulo' 'Nicolas Pepe' 'Brian Ebenezer Adjei Brobbey'
 'Daizen Maeda' 'Leandro Trossard' 'Alejandro Baena'
 'Masour Ousmane Dembele' 'Iliman Cheikh Baroy Ndiaye'
 'Riyad Karim Mahrez' 'Diogo Diogo Costa' 'Yoane Wissa'
 'Jude Victor William Bellingham' 'Petar Sucic' 'Stephen Eustaquio'
 'Henrique' 'Orlando Daniel Gill' 'Issa Laye Lucas Jean Diop'
 'Antonio Eromonsele Nordby Nusa' 'Youri Marion Tielemans'
 'Malik Leon Tillman' 'Breel Donald Embolo' 'Jhon Adolfo Arias'
 'Azz-Eddine Ounahi' 'Mikel Merino' 'Charles Marc De Ketelaere'
 'Gregor Kobel' 'Lamine Yamal Yamal' 'Julián Alvarez'
 'Pedro Antonio Porro' 'Bukayo Ayoyinka Saka' 'Ferran Torres']

Kolumna: referee_name
['Szymon Marciniak' 'Daniele Orsato' 'Michael Oliver' 'Anthony Taylor'
 'Clément Turpin' 'Danny Makkelie' 'Jesús Valenzuela' 'Wilton Sampaio'
 'César Arturo Ramos' 'Ivan Barton' 'Mustapha Ghorbal' 'Victor Gomes'
 'Ma Ning' 'Alireza Faghani' 'Yoshimi Yamashita' 'Facundo Tello'
 'João Pinheiro' 'Maurizio Mariani' 'Jalal Jayed' 'Slavko Vinčić'
 'Adham Makhadmeh' 'Saíd Martínez' 'Raphael Claus' 'Glenn Nyberg'
 'Espen Eskås' 'Yael Falcón' 'Gustavo Tejera' 'Drew Fischer'
 'Ilgiz Tantashev' 'Ismail Elfath' 'François Letexier']

===== events =====

Kolumna: minute
['17' '23' '55' '67' '74' '84' '86' '9' '59' '80' '90' '11' '21' '44' '45'
 '53' '78' '31' '7' '73' '79' '88' '14' '42' '32' '37' '43' '28' '39' '46'
 '27' '75' '38' '47' '6' '68' '50' '57' '61' '64' '83' '40' '30' '54' '16'
 '13' '19' '34' '66' '41' '89' '82' '29' '76' '60' '20' '77' '12' '36'
 '85' '72' '65' '4' '58' '33' '81' '62' '2' '56' '71' '5' '69' '3' '15'
 '10' '24' '49' '48' '87' '63' '8' '18' '106' '110' '115' '117' '120'
 '121' '22' '95' '25' '51' '103' '97' '111' '92' '70' '90+6' '1' '90+8'
 '90+1' '90+3' '35' '26' '45+2' '90+4' '105' '94' '90+5' '93' '98' '112'
 '114' '120+1' '90+2' '96' '52']

Kolumna: event_type
['Yellow Card' 'Red Card' 'VAR Review' 'Goal' 'Assist'
 'Penalty Shootout Miss' 'Penalty Shootout Goal']

===== lineups =====

Kolumna: tactical_position
['GK' 'DEF' 'MID' 'FWD']

===== team_stats =====

Kolumna: player_of_the_match
['Julián Andrés Quinones' nan 'Inbeom Hwang' 'Ismaël Kenneth Jordan Kone'
 'Folarin Jolaoluwa Balogun' 'Ibrahim Mahmoud Abunada' 'José Vinicius'
 'John McGinn' 'Nestory Irankunda' 'Kai Lukas Havertz' 'Virgil Van Dijk'
 'Yan Diomande' 'Alexander Isak' 'José Vozinha' 'Ashour Metwaly Emam'
 'Khalil Mohammed Alowais' 'Ramin Rezaeian' 'Michael Akpovie Olise'
 'Erling Braut Haaland' 'Lionel Andrés Messi' 'Iyad Ali Ali Olwan'
 'Pedro Joao Neves' 'Harry Edward Kane' 'Antoine Serlom Semenyo'
 'Luis Fernando Diaz' 'Luis Francisco Romo' 'Michal Sadilek'
 'Jonathan Christian David' 'Johan Kula Manzambi' 'Matheus Matheus Cunha'
 'Ismael Saibari' 'Matias Galarza' 'Deniz Undav' 'Eloy Victor Room'
 'Cody Mathès Gakpo' 'Ayase Ueda' 'Ali Reza Beiranvand'
 'Hamed Mahrous Mohamed Salah' 'Mikel Oyarzabal' 'Kylian Mbappe'
 'Ibrahim Maza' 'Ronaldo Cristiano Ronaldo' 'Daniel Munoz' 'Nico Oreilly'
 'Ante Budimir' 'Mateo Chavez' 'Thapelo Maseko' 'Kerim Alajbegovic'
 'Achraf Hakimi' 'Arda Guler' 'Roberto Junior Fernandez'
 'Nilson David Angulo' 'Nicolas Pepe' 'Brian Ebenezer Adjei Brobbey'
 'Daizen Maeda' 'Leandro Trossard' 'Alejandro Baena'
 'Masour Ousmane Dembele' 'Iliman Cheikh Baroy Ndiaye'
 'Riyad Karim Mahrez' 'Diogo Diogo Costa' 'Yoane Wissa'
 'Jude Victor William Bellingham' 'Petar Sucic' 'Stephen Eustaquio'
 'Henrique' 'Orlando Daniel Gill' 'Issa Laye Lucas Jean Diop'
 'Antonio Eromonsele Nordby Nusa' 'Youri Marion Tielemans'
 'Malik Leon Tillman' 'Breel Donald Embolo' 'Jhon Adolfo Arias'
 'Azz-Eddine Ounahi' 'Mikel Merino' 'Charles De Ketelaere' 'Lionel Messi'
 'Gregor Kobel' 'Lamine Yamal Yamal' 'Julián Alvarez'
 'Pedro Antonio Porro' 'Bukayo Ayoyinka Saka' 'Ferran Torres']

Kolumna: data_source
['fifa.com' 'sofascore.com' 'Sofascore']

Kolumna: last_updated
['2026-06-24' '2026-06-25' '2026-06-26' '2026-06-28' '2026-06-27'
 '2026-06-29' '2026-06-30' '2026-07-01' '2026-07-03' '2026-07-04'
 '2026-07-06' '2026-07-07' '2026-07-08' '2026-07-09' '2026-07-11'
 '2026-07-12' '2026-07-14' '2026-07-15' '2026-07-18' '2026-07-19']

===== players =====

Kolumna: player_name
['José Raúl Rangel' 'Jorge Eduardo Sanchez' 'César Jasib Montes' ...
 'Azarías Emmanuel Londono' 'Roderick Alonso Miller'
 'Jorge Abdiel Gutierrez']

Kolumna: position
['GK' 'DEF' 'MID' 'FWD']

Kolumna: data_source
['sofascore.com' nan]

Kolumna: last_verified
['2026-07-19']

===== squads =====

Kolumna: player_name
['José Raúl Rangel' 'Jorge Eduardo Sanchez' 'César Jasib Montes' ...
 'Azarías Emmanuel Londono' 'Roderick Alonso Miller'
 'Jorge Abdiel Gutierrez']

Kolumna: position
['GK' 'DEF' 'MID' 'FWD']

Kolumna: club_team
['CD Guadalajara' 'PAOK Saloniki' 'FC Lokomotiv Moscow' 'Fenerbahçe SK'
 'Genoa CFC' 'CF Cruz Azul' 'Real Betis' 'Fulham FC' 'Deportivo Toluca FC'
 'AC Milan' 'Club Santos Laguna' 'AEL Limassol' 'Club América'
 'Al Qadsiah FC' 'AEK Athens' 'Atlético De Madrid' 'Club Tijuana'
 'AZ Alkmaar' 'RSC Anderlecht' 'Pumas UNAM' 'FC Dynamo Moscow'
 'Mamelodi Sundowns FC' 'Polokwane City FC' 'Orlando Pirates FC'
 'Burnley FC' 'CD Tondela' 'Chicago Fire FC' 'Molde FK' 'Hannover 96'
 'Siwelele FC' 'Philadelphia Union' 'Kaizer Chiefs FC' 'FC Tokyo'
 'FC Midtjylland' 'Gangwon FC' 'FC Bayern München' 'Kashima Antlers'
 'Feyenoord Rotterdam' 'LAFC' 'Birmingham City FC' '1. FSV Mainz 05'
 'Wolverhampton Wanderers FC' 'Jeonbuk Hyundai Motors FC'
 'FK Austria Wien' 'Daejeon Hana Citizen FC' 'Zhejiang FC' 'Stoke City FC'
 'Be ş ikta ş  JK' 'Paris Saint-Germain' 'Celtic FC' 'Ulsan HD'
 'FK Crvena Zvezda' 'Borussia Mönchengladbach' 'Swansea City AFC'
 'PSV Eindhoven' 'SK Slavia Praha' 'TSG Hoffenheim' 'FC Hradec Králové'
 'Bayer 04 Leverkusen' 'AC Sparta Praha' 'FC Viktoria Plze ň'
 'Olympique Lyonnais' 'West Ham United FC' 'SC Braga' 'Inter Miami CF'
 'Middlesbrough FC' 'FCV Dender EH' 'US Sassuolo' 'Southampton FC'
 'Juventus FC' 'Hull City FC' 'Villarreal CF' 'Rangers FC' 'OGC Nice'
 'Orlando City SC' 'Barnsley' 'Norwich City FC' 'Toronto FC'
 'HNK Hajduk Split' 'Royale Union Saint-Gilloise' 'Austin FC'
 'FC St. Pauli' 'Gaziantep FK' 'UC Sampdoria' 'Atalanta Bergamo'
 'Brøndby IF' 'SL Benfica' 'BSC Young Boys' 'Jagiellonia Bia ł ystok'
 'VfB Stuttgart' 'FC Schalke 04' 'FK Borac Banja Luka' 'FC Astana'
 'Pafos FC' 'Karlsruher SC' 'FC Red Bull Salzburg' 'HNK Rijeka'
 'SK Sturm Graz' 'Universitatea Cluj' 'FC Slovan Liberec' 'Al Rayyan SC'
 'Al Sadd SC' 'Al Wakrah SC' 'Al Arabi SC' 'Al Duhail SC' 'Al Gharafa SC'
 'Cultural Leonesa' 'Al Shamal SC' 'Borussia Dortmund' 'Hamburger SV'
 'FC Internazionale Milano' 'AS Monaco' 'Stade Rennais FC' 'Bologna FC'
 'SC Freiburg' 'Sunderland AFC' 'Nottingham Forest FC' 'FC Lorient'
 'Sevilla FC' 'Valencia CF' 'Leeds United FC' 'Pisa SC' 'FC Augsburg'
 'Eintracht Frankfurt' 'Fortuna Düsseldorf' 'Liverpool FC' 'Arsenal FC'
 'Manchester United FC' 'CR Flamengo' 'Real Madrid C. F.'
 'Newcastle United FC' 'Santos FC' 'FC Barcelona' 'Grêmio FBPA'
 'FC Zenit St. Petersburg' 'Al Ittihad' 'Botafogo' 'Al Ahli FC'
 'Brentford FC' 'AFC Bournemouth' 'Al Hilal SC' 'Al Fateh SC' 'Lille OSC'
 'Girona FC' 'Al Ain FC' 'RS Berkane' 'KRC Genk' 'RC Strasbourg'
 'Angers SCO' 'Crystal Palace FC' 'Al Ahly FC' 'Olympiacos FC' 'ASFAR'
 'AS Roma' 'KV Mechelen' 'SC Bastia' 'LDU Quito' 'FC Lugano'
 'El Paso Locomotive FC' 'AS Nancy' 'Esteghlal Tehran FC' 'FC Dallas'
 'FC Sochaux-Montbéliard' 'Colorado Springs Switchbacks FC'
 'Almere City FC' 'Ferencvárosi TC' 'FC Vizela' 'Çaykur Rizespor'
 'AJ Auxerre' 'KAA Gent' 'FC Cosmos Koblenz' 'SV Zulte Waregem'
 'FC Tatran Pre š ov' 'Violette AC' 'SSC Napoli' 'Hibernian FC'
 'Aston Villa FC' 'Charlton Athletic FC' 'Torino FC' 'Al Ettifaq FC'
 'Wrexham AFC' 'Ipswich Town FC' 'Heart Of Midlothian FC' 'Everton FC'
 'Kilmarnock FC' 'GNK Dinamo Zagreb' 'New England Revolution'
 'FC Cincinnatti' 'Charlotte FC' 'Vancouver Whitecaps FC'
 'Seattle Sounders FC' 'Columbus Crew' 'Coventry City FC'
 'Olympique Marseille' 'Toulouse FC' 'New York City FC' 'Cerro Porteño'
 'Atlético Mineiro' 'SE Palmeiras' 'Brighton & Hove Albion FC'
 'US Cremonese' 'Atlanta United FC' 'CA San Lorenzo' 'CA Lanús'
 'São Paulo FC' 'CS Independiente Rivadavia' 'CA Independiente'
 'Club Olimpia' 'Portsmouth FC' 'Red Bull Bragantino' 'CA Talleres'
 'Levante UD' 'APOEL FC' 'Parma' 'Grazer AK' 'Albirex Niigata'
 'Melbourne City FC' 'SC Heracles Almelo' 'CD Castellón' 'Randers FC'
 'Watford FC' 'Leicester City FC' 'Melbourne Victory FC' 'Sydney FC'
 'Colorado Rapids' 'FC Machida Zelvia' 'FC Porto' 'Galatasaray SK'
 'Kasımpa ş a SK' 'RB Leipzig' 'Miami FC' 'Sparta Rotterdam' 'Abha Club'
 'RKC Waalwijk' 'PEC Zwolle' 'FC Volendam' 'FC Zürich' 'I ğ dır FK'
 'AE Kifisia FC' 'SC Telstar' 'Maccabi Haifa FC' 'Rotherham United FC'
 'SK Beveren' 'Terengganu FC' 'Kayserispor' 'Shefield United FC'
 'FC Den Bosch' 'Konyaspor' 'NEC Nijmegen' 'VVV Venlo' 'Sporting CP'
 'Gil Vicente FC' 'NK Maribor' 'Ba ş ak ş ehir FK' 'Cercle Brugge'
 'Sporting Charleroi' 'Panathinaikos FC' 'Trabzonspor' 'CA Huracán'
 'SC Internacional' 'Club Brugge' 'Independiente Del Valle'
 'Royal Antwerp FC' 'Venezia FC' 'CA River Plate' 'CF Pachuca'
 'Chelsea FC' 'Manchester City FC' 'AFC Ajax' 'SC Corinthians'
 'Tottenham Hotspur FC' 'SV Werder Bremen' 'Sint-Truiden VV'
 'Real Sociedad' 'Sanfrecce Hiroshima' 'Stade Reims' 'Le Havre AC'
 'FC København' 'VfL Wolfsburg' 'Derby County FC' 'RC Celta Vigo'
 'Udinese' 'Holstein Kiel' 'AIK Stockholm' 'Mjällby AIF' 'Malmö FF'
 'Club Africain' 'Servette FC' 'FC Dynamo Makhachkala'
 '1. FC Union Berlin' 'CS Sfaxien' 'Espérance De Tunisie'
 'Étoile Du Sahel' 'IFK Norrköping FK' 'US Monastir' 'Zamalek SC'
 'Pyramids FC' 'Real Oviedo' 'Al Najmah SC' 'FC Nordsjælland' 'ZED FC'
 'El Gouna FC' 'Tractor Sazi Tabriz FC' 'Sepahan SC' 'Persepolis FC'
 'Shabab Al Ahli Club' 'FC Rostov' 'Al Nasr SC' 'Al Ittihad Kalba SCC'
 'Foolad Khuzestan FC' 'Al Wahda SC' 'Standard Liège' 'Malavan Anzali FC'
 'Millwall FC' 'Wellington Phoenix FC' 'Auckland FC' 'Minnesota United FC'
 'Viking Stavanger' 'Motherwell FC' 'Lechia Gda ń sk' 'Portland Timbers'
 'WS Wanderers FC' 'Port Vale FC' 'AS Saint-Etienne' 'Silkeborg IF'
 'Newcastle United Jets FC' 'Braintree Town FC' 'Athletic Club'
 'CA Osasuna' 'GD Chaves' 'SCU Torreense' 'Al Bataeh Club'
 'Shamrock Rovers FC' 'FC Krasnodar' 'CF Estrela Da Amadora' 'FC FCSB'
 'FC Akron Tolyatti' 'Apollon Limassol' 'PFC Montana'
 'PFC Ludogorets Razgrad' 'Puskás Akadémia FC' 'SC Farense' 'AC Omonia'
 'Vitória SC' 'Casa Pia AC' 'San Diego FC' 'SJK' 'Maccabi Tel-Aviv FC'
 'Al Nassr FC' 'RC Lens' 'Neom SC' 'Al Ula Saudi FC' 'CF Monterrey'
 'Fluminense FC' 'Tigres UANL' 'Estudiantes LP' 'Real Salt Lake'
 'Rayo Vallecano' 'Como' 'Samsunspor' 'Al Talaba SC' 'Port FC'
 'Pogo ń  Szczecin' 'Pakhtakor Tashkent FK' "Al Zawra'a SC" 'Al Shorta SC'
 'AEK Larnaca FC' 'Al Dhafra SCC' 'Luton Town FC' 'Dibba FC'
 'Nashville SC' 'FC Utrecht' 'Al Karma SC' 'KS Cracovia' 'Aarhus GF'
 'Sarpsborg 08 FF' 'Persib Bandung' 'FK Bodø/Glimt' 'CA Boca Juniors'
 'FC Stade Nyonnais' 'USM Alger' 'JS Kabylie' 'FC Twente' 'Györi ETO FC'
 'Hellas Verona FC' 'Granada CF' 'Frosinone' 'Paris FC' 'Elche CF'
 'LASK Linz' 'Wolfsberger AC' 'Al Hussein SC' 'Al Faisaly SC' 'FC Seoul'
 'Raja Casablanca' 'Selangor FC' 'Al Sailiya SC' 'Al-Quwa Al-Jawiya'
 'Qatar SC' 'Al Wahdat SC' 'Al Shabab FC' 'RCD Mallorca' 'Widzew Ł ód ź'
 'AEL FC' 'Montpellier HSC' 'Atromitos FC' 'FC Spartak Moscow'
 'Alanyaspor' 'FC Noah' 'RCD Espanyol' 'Al Jazira' 'Aris Limassol FC'
 'PFC Navbahor Namangan' "FK Neftchi Farg'ona" 'Baniyas Club'
 'Nasaf Qarshi FC' 'FK Dinamo Samarkand' 'FK Buxoro' 'Surkhon FK'
 'OKMK FK' 'Atlético Nacional' 'Atlas FC' 'Cagliari' 'Racing Santander'
 'Athletico Paranaense' 'CA Rosario Central' 'FC Nantes'
 'CA Vélez Sarsfield' 'CR Vasco Da Gama' 'ACF Fiorentina' 'FC St. Gallen'
 "St Patrick's Athletic FC" 'Hearts Of Oak SC' 'Club Nacional'
 'Š K Slovan Bratislava' 'Deportivo Saprissa' 'FC Pari Nizhny Novgorod'
 'Hapoel Kiryat Shmona FC' 'FC Juárez' 'Club León' 'Mazatlán FC'
 'CD Marathón' 'Puerto Cabello CF' 'CD Plaza Amador'
 'CD Universidad Católica' 'CD Universidad De Concepción' 'CD Cobresal'
 'Al Fayha FC' 'Turan Tovuz' 'Deportivo La Guaira']

Kolumna: date_of_birth

In [ ]:
matches_detailed["kickoff_time_utc"] = pd.to_datetime(matches_detailed["kickoff_time_utc"], utc=True)

/tmp/ipykernel_628/3191285924.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  matches_detailed["kickoff_time_utc"] = pd.to_datetime(matches_detailed["kickoff_time_utc"], utc=True)

In [ ]:
print(matches["kickoff_time_utc"].unique()[:10])

['19:00' '23:00' '15:00' '18:00' '21:00' '23:59' '22:00' '12:00' '02:30'
 '07:00']

In [ ]:
matches["date"] = pd.to_datetime(matches["date"])

In [ ]:
matches_detailed["date"] = pd.to_datetime(matches_detailed["date"])

In [ ]:
squads["date_of_birth"] = pd.to_datetime(squads["date_of_birth"])

In [ ]:
players["last_verified"] = pd.to_datetime(players["last_verified"])

In [ ]:
team_stats["last_updated"] = pd.to_datetime(team_stats["last_updated"])

In [ ]:
team_stats.head()

,match_id,team_id,possession_pct,total_shots,shots_on_target,corners,fouls,offsides,saves,player_of_the_match,data_source,last_updated
0,1,1,57,16,4,6,11,2,1,Julián Andrés Quinones,fifa.com,2026-06-24
1,1,2,43,3,2,3,15,1,4,NaN,fifa.com,2026-06-24
2,2,3,54,12,5,4,10,1,2,Inbeom Hwang,sofascore.com,2026-06-24
3,2,4,46,10,3,3,13,2,4,NaN,sofascore.com,2026-06-24
4,3,5,52,13,4,9,12,2,3,Ismaël Kenneth Jordan Kone,fifa.com,2026-06-24

In [ ]:
players.head()

,player_id,player_name,team_id,position,matches_played,matches_started,minutes_played,goals,assists,shots,...,yellow_cards,red_cards,penalty_goals,own_goals,clean_sheets,saves,goals_conceded,average_rating,data_source,last_verified
0,1,José Raúl Rangel,1,GK,5,5,438,0,0,NaN,...,0,0,0,0,4.0,7.0,3.0,NaN,sofascore.com,2026-07-19
1,2,Jorge Eduardo Sanchez,1,DEF,4,4,349,0,1,NaN,...,1,0,0,0,NaN,NaN,NaN,NaN,sofascore.com,2026-07-19
2,3,César Jasib Montes,1,DEF,4,4,315,0,0,NaN,...,0,1,0,0,NaN,NaN,NaN,NaN,sofascore.com,2026-07-19
3,4,Edson Omar Alvarez,1,DEF,4,2,239,0,0,NaN,...,1,0,0,0,NaN,NaN,NaN,NaN,sofascore.com,2026-07-19
4,5,Johan Felipe Vasquez,1,DEF,4,4,360,0,0,NaN,...,1,0,0,0,NaN,NaN,NaN,NaN,sofascore.com,2026-07-19

In [ ]:
dfs = {"matches":matches,
"matches_detailed":matches_detailed,
"events":events,
"lineups":lineups,
"team_stats":team_stats,
"players":players,
"squads":squads,
"teams":teams,
"venues":venues,
"stages":stages,
"referees":referees,
       }

for name, df in dfs.items():
    object_cols = df.select_dtypes(include=["object"]).columns
    df[object_cols] = df[object_cols].astype("string")
    print(f"{name}: przekonwertowano {len(object_cols)} kolumn")

matches: przekonwertowano 3 kolumn
matches_detailed: przekonwertowano 14 kolumn
events: przekonwertowano 2 kolumn
lineups: przekonwertowano 1 kolumn
team_stats: przekonwertowano 2 kolumn
players: przekonwertowano 3 kolumn
squads: przekonwertowano 3 kolumn
teams: przekonwertowano 5 kolumn
venues: przekonwertowano 3 kolumn
stages: przekonwertowano 1 kolumn
referees: przekonwertowano 2 kolumn

In [ ]:

folder = r"C:\Users\Mazur&Ewela\Desktop\Projekty PowerBI\mistrzostwa swita pilak nozna 2026 konkurs\obrobione datasety"

dfs = {"matches":matches,
"matches_detailed":matches_detailed,
"events":events,
"lineups":lineups,
"team_stats":team_stats,
"players":players,
"squads":squads,
"teams":teams,
"venues":venues,
"stages":stages,
"referees":referees,
       }
os.makedirs(folder, exist_ok=True)

for name, df in dfs.items():
    path = os.path.join(folder, f"{name}.csv")

    df.to_csv(
        path,
        index=False,
        encoding="utf-8-sig"
    )

In [ ]:
import os

print(os.listdir())

['.config', 'venues.csv', 'referees.csv', 'tournament_stages.csv', 'match_prediction_features.csv', 'match_lineups.csv', 'player_stats.csv', 'matches_detailed.csv', 'teams.csv', 'squads_and_players.csv', 'matches.csv', 'match_events.csv', 'match_team_stats.csv', 'sample_data']

In [ ]:
from google.colab import files

files.download("teams.csv")
files.download("matches.csv")
files.download("matches_detailed.csv")
files.download("match_events.csv")
files.download("match_lineups.csv")
files.download("match_team_stats.csv")
files.download("player_stats.csv")
files.download("squads_and_players.csv")
files.download("venues.csv")
files.download("tournament_stages.csv")
files.download("referees.csv")